### ISSUE TITLE
[BUG]: The version of Node.js installed with Raspbian OS is EOL

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#117]
### Description of the bug

I prepared a Raspberry Pi following the instructions at <https://arneis.readthedocs.io/en/latest/howto/howto-prepare-rpi4b-for-arneis.html>.

Unfortunately the installed distribution comes with Node.js already installed but in an older and no longer maintained version (v10.24.0) which causes a few packages to fail - most notably, [Next.js](https://nextjs.org/)

### Steps To Reproduce

1. Prepare a Raspberry Pi following the instructions at <https://arneis.readthedocs.io/en/latest/howto/howto-prepare-rpi4b-for-arneis.html>
2. Login as pi@raspberry (or open a local terminal) and type the following commands:

```bash
node --version
npm --version
```
### Expected result

A recent version of Node.js (example 14.x) and npm are displayed

### Actual result

```text
pi@rpird102:~ $ node --version
v10.24.0
pi@rpird102:~ $ npm --version
5.8.0
pi@rpird102:~ $
```

### Additional Information

Please refer to <https://nodejs.org/en/about/releases/> for the support roadmap of Node.js versions

**Comment by gteti** [comment]
You probably have to curl an higher version of Node which is compatible with RPi.

**Comment by gmacario** [comment]
> You probably have to curl an higher version of Node which is compatible with RPi. https://github.com/nodesource/distributions/tree/master/deb

Thanks for your suggestion @gteti.

As a matter of fact the bug I have created is because I could not understand **why** such an old version of Node.js was installed on this device (`rpird102`).

I double checked on the device which was used to write [the HOWTO](https://arneis.readthedocs.io/en/latest/howto/howto-prepare-rpi4b-for-arneis.html) but apparently there is no node command installed there:

```text
pi@rpi4gm35:~ $ dpkg -l | grep node
pi@rpi4gm35:~ $ node --version
-bash: node: command not found
pi@rpi4gm35:~ $
```

**Comment by gmacario** [comment]
After checking with other installations of Raspberry Pi OS it looks like there are no reasons why such an old version of nodejs was installed.

Remove old version of Node, install Node.js 14.x as described in <https://www.w3schools.com/nodejs/nodejs_raspberrypi.asp>

```bash
sudo apt update && sudo apt remove --purge nodejs && sudo apt autoremove --purge
mkdir -p ~/Downloads && cd ~/Downloads
curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install -y nodejs
```

Test:

```text
pi@rpird102:~ $ node --version
v14.19.0
pi@rpird102:~ $ npm --version
6.14.16
pi@rpird102:~ $
```
