### ISSUE TITLE
[FEAT]: Source T-shirts for the team members

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#121]
### Description

In preparation to the [2022-02-17 OpenCV Weekly Webinar](https://github.com/B-AROL-O/ARNEIS/issues/120) and other future public showcases of the ARNEIS project, I believe it would be great if all the team members wear some unique piece of garment (i.e. a T-shirt or a hoodie), featuring either the [ARNEIS logo](https://github.com/B-AROL-O/ARNEIS/issues/24) or the [B-AROL-O Team logo](https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/Barolo_logo_shade.svg).

**Comment by gmacario** [comment]
Here are some sites of companies printing customized t-shirts where we may ask for a quote:

- <https://www.stickermule.com/it/products/magliette-personalizzate> (produzione entro 4 giorni e spedizione gratuita)
- <https://camaloon.it/magliette-personalizzate>(forse piu' indicato per volumi)
- ...
-

**Comment by gmacario** [comment]
Just for fun I submitted a quote to <https://www.stickermule.com/>. Here is the result:

![image](https://user-images.githubusercontent.com/75182/152638521-11d7a245-cd7d-4e00-9039-63dea981bd30.png)

By the way, which is your T-Shirt size? Personally, I wear a 2XL.

**Comment by gmacario** [comment]
Not urgent, we already have a lot on the plate for this week. Postponing after the 2022-02-17 webinar

**Comment by alv67** [comment]
On saturday 2022-03-05 checked in a local store the possibility to print t-shirts for our goal.

![image](https://user-images.githubusercontent.com/25162080/156896670-f668534c-cb9a-4bae-a846-87438235f9e2.png)

Unlikely in this laboratory they can only print on white shirts and not over colored shirts. Their technology is thermal transfer: they print on white paper the Logo and when transferred to the t-shirt also the white background is transferred.

The cost is 15.5€ per shirt (1 t-shirt).

Next Step : check for online laboratories.

**Comment by gmacario** [comment]
Last night I had an idea for improvement: Why on the T-Shirts couldn't we print a QRCode linking to <https://arneis.readthedocs.io> close to ARNEIS logo - or maybe, on the back of the T-Shirt if this does not add too many extra costs?

For the tool to be used I would recommend https://devpost.com/software/axolotl

**Comment by alv67** [comment]
Order of t-shirt from <https://camaloon.it/>. 
More information about prices and order in [private project](https://github.com/B-AROL-O/opencv-spatial-ai-contest)

Image of the ordered t-shirt
![IMAGE 2022-03-23 20:18:12](https://user-images.githubusercontent.com/25162080/159778886-06b54b2d-e392-48fa-9ffc-bdf1b78ec663.jpg)
