### ISSUE TITLE
[FEAT]: Evaluate Roboflow for training ARNEIS NN

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#123]
### Description

Evaluate [Roboflow](https://roboflow.com/) for training ARNEIS NN in alternative to using https://github.com/luxonis/depthai-ml-training

### Additional Information

https://roboflow.com/

**Comment by gmacario** [comment]
From <https://github.com/luxonis/depthai-ml-training>

> ## Check Out RoboFlow!
>
> We at Luxonis encourage our users to try out [RoboFlow](https://roboflow.com/) for annotating, training and deploying their ML models, especially if you are new to the ML world. They have created a [course for the DepthAI platform](https://roboflow.com/course) that is a great starting point for everyone. They also have two blog posts, [quickstart guide](https://blog.roboflow.com/deploy-luxonis-oak/) and training [custom object detection model](https://blog.roboflow.com/luxonis-oak-d-custom-model/) with their platform, which are both tailored for DepthAI devices.

**Comment by gmacario** [comment]
Deferring to next week

**Comment by gmacario** [comment]
As hinted by Phil Nelson during the 2022-02-17 OpenCV Weekly Webinar

> You can try Roboflow by visiting the following URL: <https://www.roboflow.com/opencv>

**Comment by gteti** [comment]
I'll try to look into it this week.

**Comment by gmacario** [comment]
@gteti Re: Deployment of a Roboflow model on an Edge Device such as the OAK-D-Lite is shown at TODO from 40:31

**Comment by gteti** [comment]
Yes
As I verabally mentioned, there are two way to use roboflow trained models.
1- Use the API and send each saved frame as jpg, bmp,.. to their server. Your trained model will respond with prediction. https://docs.roboflow.com/python
2- Use the docker roboflow instance that should download your model locally so it's possible to do offline object recognition https://docs.roboflow.com/inference/luxonis-oak

**Comment by gteti** [comment]
The training on roboflow is made to their own model (I have the public feature for my account). So I've learned all I could on this matter. Closing
