### ISSUE TITLE
[FEAT]: Learn how to create images automatically with associated xml

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#128]
### Description

Learn how to create images more automatically with associated xml to be able to use that with the training of NN. This is blocking #31

**Comment by gteti** [comment]
First test with the code implemented.
![immagine](https://user-images.githubusercontent.com/51110452/152658666-a53a3a9c-feec-442f-b4c4-c5229536de99.png)

In the left side my created XML. In the right side one of the xml to be used for the training through the notebook example.

**Comment by gteti** [comment]
I have to still fix a problem with path + file names.

**Comment by gmacario** [comment]
Moving to next sprint

**Comment by gteti** [comment]
Implemented in the code.
