### ISSUE TITLE
[Event]: San Mauro Brick Show 2022

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#130]
### Description

Event organized by [Piemonte Bricks LUG](https://www.facebook.com/piemontebricksLUG/)

* Location: Palazzetto dello Sport - Via Luigi Burgo, San Mauro Torinese (TO)
* Dates:
   - Saturday, 2022-04-09 14:30-19:00 CEST
   - Sunday, 2022-04-10 10:00-18:30 CEST
* Hashtag: `#roadtosanmauropiuchemai`

### Official poster

[![IMG-20220323-WA0004](https://user-images.githubusercontent.com/75182/160247180-c4eaea7d-c804-41d7-ac84-f2d59346f0dd.jpg)](https://www.torinotoday.it/eventi/san-mauro-brick-show-9-10-aprile.html)

### Additional Information

The event was initially scheduled for 2022-02-19 and 2022-02-20 but was then posponed due to COVID-19 restrictions.

**Comment by gmacario** [comment]
We decided that the B-AROL-O team will participate to the event and will showcase the ARNEIS project.

@gmacario will follow-up with the event organizers and submit the requested paperwork ASAP.

**Comment by gmacario** [comment]
Hello,

Due to personal reasons I will not be able to attend our booth on Sunday, 2022-04-10 around lunch time.
Is there anyone from our friends and supporters who can help @gteti in attending the booth?

As a reward I promise that the B-AROL-O team may offer him/her the lunch.

Please comment if interested.

**Comment by gteti** [comment]
I was also invited to launch on Sunday 2022-04-10 but ok, I'll be in the booth. No need to ask to other people.

**Comment by gmacario** [comment]
Thanks @gteti but I would try to find at least another person who will stay with you, I have been showcasing at trade shows many times and I know it could be tiresome to be alone when there is a lot of crowd.

Let us keep the issue open, we shall close it on Sunday when the event is over

**Comment by gmacario** [comment]
As agreed yesterday when celebrating @mmaruf graduation:

- @gteti and @gmacario will setup ARNEIS stand and will attend all Saturday. We will also have lunch and dinner (paid by @B-AROL-O/arneis-core) together with the other exhibitors
- On Sunday morning (opening 10:00) @gteti will be alone until @pitdagosti arrives. They will have lunch (paid by @B-AROL-O/arneis-core together with the other exhibitors)
- @gmacario will arrive on Sunday afternoon, will attend the booth until closure (18:30) then will pack all the stuff and return back home.

All the people, friends and families who happen to drop by are kindly invited to takes photos, videos, tweet, make blog posts, etc and share them on social media with the following tags: #ARNEIS #OAKDLiteContest #roadtosanmauropiuchemai

**Comment by gteti** [comment]
> As agreed yesterday when celebrating @MarcoMaru graduation party:
> 
>     * @gteti and @gmacario will setup ARNEIS stand and will attend all Saturday. We will also have lunch and dinner (paid by @B-AROL-O/arneis-core) together with the other exhibitors
> 
>     * On Sunday morning (opening 10:00) @gteti will be alone until @pitdagosti arrives. They will have lunch (paid by @B-AROL-O/arneis-core together with the other exhibitors)
> 
>     * @gmacario will arrive on Sunday afternoon, will attend the booth until closure (18:30) then will pack all the stuff and return back home.
> 
> 
> **IMPORTANT**: All the people, friends and families who happen to drop by are kindly invited to take photos, videos, tweet, make posts on Facebook, LinkedIn, Instagram, etc and share them on social media with the following tags: `#ARNEIS` `#OAKDLiteContest` `#roadtosanmauropiuchemai`

You said you will arrive at 14:00.

**Comment by gmacario** [comment]
The event took place and was a success!
