### ISSUE TITLE
[FEAT]: Create a VM on Azure for training the ARNEIS NN

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#153]
### Description

As discussed yesterday @gteti needs a login with sudo privileges to a VM instance on Azure where he can train the Neural Network for the ARNEIS project.

The VM shall be accessible via SSH. 

### Additional Information

Create the VM following the instructions at https://arneis.readthedocs.io/en/latest/howto/howto-create-vm-on-azure.html

@gteti public SSH key is available at #98

**Comment by gteti** [comment]
I didn't ask for one 😄

**Comment by gmacario** [comment]
@gteti I have created a VM following the instructions at https://arneis.readthedocs.io/en/latest/howto/howto-create-vm-on-azure.html and gave you sudo privileges.

You should be able to login using your SSH key - I have provided you with the username and the hostname of the VM in a private message.

Please check and close this AI once you may successfully login. Thanks!

**Comment by gteti** [comment]
Thank you, I can login now
