### ISSUE TITLE
[FEAT]: Try creating diagrams using Mermaid

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#179]
### Description

GitHub [recently announced the integration of Mermaid](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/). Let us see whether this can be useful to include diagrams into markdown pages and if this also works on <https://arneis.readthedocs.io>.

### Additional Information

Other links:

* https://ardalis.com/github-diagrams-with-mermaid/
* https://github.com/mermaid-js/mermaid
* https://github.com/github/roadmap/issues/372
* https://mermaid-js.github.io/
* https://www.youtube.com/watch?v=-HUwt8dF4X8

**Comment by pitdagosti** [comment]
Hi! I just published a tutorial to use the mermaid graphic tool [here](https://github.com/pitdagosti/Bluetooth/blob/main/docs/tutorials/mermaid-howto.md).

I hope you find it useful!

**Comment by gmacario** [comment]
> Hi! I just published a tutorial to use the mermaid graphic tool [here](https://github.com/pitdagosti/Bluetooth/blob/main/docs/tutorials/mermaid-howto.md).
> 
> I hope you find it useful!

Yes, it is!

Would you mind submitting a Pull Request to ARNEIS repo in order to have it listed as an ARNEIS official HOWTO?

**Comment by pitdagosti** [comment]
Sure 😄 I'll do it asap

**Comment by gmacario** [comment]
> Sure 😄 I'll do it asap

@pitdagosti I got lost: did you eventually submit the PR? If so, where is it?

**Comment by gmacario** [comment]
> > Sure 😄 I'll do it asap
> 
> @pitdagosti I got lost: did you eventually submit the PR? If so, where is it?

Never mind. The result is now maintained at https://github.com/B-AROL-O/ARNEIS/blob/main/docs/howto/howto-use-mermaid-graphic-tool.md
