### ISSUE TITLE
[BUG]: Build of main branch fails on readthedocs.org

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#186]
### Description of the bug

See https://readthedocs.org/projects/arneis/builds/16147498/

### Steps To Reproduce

1. Just look at https://readthedocs.org/projects/arneis/builds/

**Comment by gmacario** [comment]
@alv67 do you have any ideas of what could have gone wrong?

**Comment by gmacario** [comment]
The first failed build of "version latest" was this one
https://readthedocs.org/projects/arneis/builds/16141262/

**Comment by alv67** [comment]
No idea. Apart for the TODO warnings, I don’t see other errors. But the TODO warning are present in other commit
Il 21 feb 2022, 07:03 +0100, Gianpaolo Macario ***@***.***>, ha scritto:

**Comment by alv67** [comment]
Try this [arneis-alv67.readthedocs.io](https://arneis-alv67.readthedocs.io/en/bug-readthedocs-fix/)

where I tried to solve the problem (disabling PDF export) via a .readthedocs.yaml configuration file.
I tried also to force a python 3.9 version but that was not the solution.

**Comment by gmacario** [comment]
> Try this [arneis-alv67.readthedocs.io](https://arneis-alv67.readthedocs.io/en/bug-readthedocs-fix/)
> 
> where I tried to solve the problem (disabling PDF export) via a .readthedocs.yaml configuration file.

Uhm, so the problem most likely lies in the PDF generation (or maybe the intermediate conversion to LaTeX file format).

> If you agree I can PR this solution

Yes, please!
Later we will address how to generate the PDF again.
