### ISSUE TITLE
[FEAT]: arneis.readthedocs.io: Restore PDF document generation

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#191]
### Description

The fix to https://github.com/B-AROL-O/ARNEIS/issues/186 introduced in PR https://github.com/B-AROL-O/ARNEIS/pull/190 had the consequence of disabling the PDF document generation of the ARNEIS RTD site.

This task has the goal of restoring the functionality without introducing further regressions.

**Comment by alv67** [comment]
@gmacario you closed the wrong item..

**Comment by gmacario** [comment]
> @gmacario you closed the wrong item..

Thanks for pointing it out to me. Reopening

**Comment by gmacario** [comment]
@alv67 as soon as you are done with #46 would you able to make a quick fix under /docs in order to restore the possibility to export https://arneis.readthedocs.io?

For me the resolution of this issue is a blocker for Release 1.0

**NOTE**: As we agreed during our latest sprint planning meeting if PDF can be generating by leaving out some pages (for instance, TODO) I am totally fine with it. This is exactly what I keep telling my two kids: if one prevents the others to show their best, do all what you can to get rid of them.

CC: @gteti, @MarcoMaru, @DavideMacario
