### ISSUE TITLE
[BUG]: Wide table handling on `arneis.readthedocs.io`

### ISSUE THREAD

**Issue by alv67** [B-AROL-O/ARNEIS#194]
### Description of the bug

Wide table does not show in [Unboxing LEGO® Set 42100](https://arneis.readthedocs.io/en/latest/lego-set-42100/unboxing-lego-set-42100.html).

### Steps To Reproduce

See [Unboxing LEGO® Set 42100](https://arneis.readthedocs.io/en/latest/lego-set-42100/unboxing-lego-set-42100.html).

**Comment by gmacario** [comment]
Comparing https://arneis--195.org.readthedocs.build/en/195/lego-set-42100/unboxing-lego-set-42100.html

![image](https://user-images.githubusercontent.com/75182/155271226-ab27bb88-5739-4714-b922-1f02a85f710f.png)

to original https://arneis.readthedocs.io/en/latest/lego-set-42100/unboxing-lego-set-42100.html

![image](https://user-images.githubusercontent.com/75182/155271253-5eb6e2d7-cd56-4f58-9e14-45275598d905.png)

**Comment by gmacario** [comment]
The fix is also working well when the page is displayed on a mobile phone (although here scrolling horizontally is still necessary)

![2022-02-23 07 33 36](https://user-images.githubusercontent.com/75182/155271637-b1ac5844-8eba-4bd9-989e-de94ac3aa084.jpg)

Merging PR. Thanks @alv67 for the fix!
