### ISSUE TITLE
[Event]: Attend event "Villaggio Leumann in Bricks 2022"

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#208]
### Description

Event organized by [Piemonte Bricks LUG](https://www.facebook.com/piemontebricksLUG/)

* Location: Villaggio Leumann, Collegno (TO)
* Dates: 
   - Saturday, 2022-04-02 14:30-19:30 CEST
   - Sunday, 2022-04-03 10:30-18:30 CEST

### Additional Information

![image](https://user-images.githubusercontent.com/75182/155856842-e33527ed-3abb-461d-bfd4-1ee829fb555e.png)

**Comment by gmacario** [comment]
Based on the decision to participate to #130 we will not have an active participation here.

However it time permits it would be good to visit the show and maybe have a quick conversation with the organizers (the same of #130)

**Comment by gteti** [comment]
I will go there. Can we decide on a day and time so we can meet there ?

**Comment by gmacario** [comment]
Hi @alv67 and @gteti I am still unsure I did not get COVID, therefore I would skip the visit to Villaggio Leumann.

In any case I hope I will fully recover for Saturday afternoon at San Mauro, or - even earlier - for Friday, 2022-04-08 15:00 CET at Toolbox Torino ;-)

**Comment by gmacario** [comment]
The event took place, and as far as I know only @alv67 was able to attend.

Closing, please comment in case anyone has anything to say about this event
