### ISSUE TITLE
[Event]: Expo Mattoncino 6 Pinerolo

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#213]
### Description

* Location: Centro Commerciale Le Due Valli - Via Cascina Vastameglio, 3 - Pinerolo (TO)
* Dates: Saturday, 2022-05-28 and Sunday, 2022-05-29

**Comment by gmacario** [comment]
Event date and location confirmed
https://www.facebook.com/events/1135159887297021

![image](https://user-images.githubusercontent.com/75182/156034883-63d09dd1-4794-4ed3-887e-34acce647701.png)

**Comment by gmacario** [comment]
We decided that the B-AROL-O team will participate to the event and will showcase the ARNEIS project.

@gmacario will follow-up with the event organizers and submit the requested paperwork ASAP.

**Comment by gmacario** [comment]
Da: Gianpaolo Macario <gmacario@xxxx.com>
Date: mer 2 mar 2022 alle ore 22:44
Subject: Iscrizione Expo Mattoncino 6 - Macario Gianpaolo con Progetto ARNEIS
To: To Make comm.le <tomake.commerciale@xxxx.com>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>, Filippo Macario <filippo.macario@xxxx.it>
Attachment: 2022-03-02-iscrizione-expo-mattoncino-6.pdf (4,774K)

Buonasera Manuela,

Come da accordi intercorsi invio in allegato modulo di iscrizione compilato e sottoscritto, piu' regolamento sottoscritto in segno di accettazione.

Sperando che la nostra richiesta possa essere accolta, auguro una buona serata

--
Gianpaolo Macario
cell: xxx-xxxx
email: gmacario@xxxx.com

**Comment by gmacario** [comment]
https://www.satyrnet.it/expo-mattoncino-2022-pinerolo/

**Comment by gmacario** [comment]
Here is the audio jingle about Expo Mattoncino:

https://www.dropbox.com/s/tbvk8vn2u9hq126/AUD-20220427-WA0070.mp3?dl=0

**Comment by gteti** [comment]
Has discussed we have agreed on 
- May 28th: Myself, Alessandro and Pietro will go and build the stand and stay the day.
- May 29th: Gianpaolo will attend, hopefully with someone else too.

**Comment by gmacario** [comment]
Unfortunately we will not be able to attend. Closing
