### ISSUE TITLE
[FEAT]: Update ARNEIS screenshot on home page of GitHub and ReadTheDocs

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#239]
### Description

Now that we have merged #201 and #238 we should probably also revamp the first image in the landing page of

* https://github.com/B-AROL-O/ARNEIS
* https://arneis.readthedocs.io/

@alv67 and @gteti which one would you choose?

**Comment by gmacario** [comment]
> @alv67 and @gteti which one would you choose?

Personally, I would do the following:

1. Replace the video at the top of the page with the [ARNEIS logo](https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/Arneis_logo_.svg)
2. Place the [rotating MOC](https://github.com/B-AROL-O/ARNEIS/blob/main/mocs/project/arneis-conveyor-20220312.gif) later in the page

   ![arneis-conveyor-20220312.gif](https://github.com/B-AROL-O/ARNEIS/raw/main/mocs/project/arneis-conveyor-20220312.gif)

**Comment by alv67** [comment]
I agree with you @gmacario
