### ISSUE TITLE
Create logo for the ARNEIS project

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#24]
We should develop a (non-copyrighted by others) logo for the [ARNEIS](https://github.com/B-AROL-O/ARNEIS) project.

Basic requirements:

* [ ] The logo should be an original artwork. The author must submit a [Certificate of Authenticity](https://www.format.com/magazine/resources/art/certificates-of-authenticity) as part of the Pull request
* [ ] Alternatively, the logo could be a derivative work based on material licensed under either the CC0 or Public Domain licenses. If so, please make sure the upstream URL is mentioned in the CoA
* [ ] The logo must not infringe third party trademarks and copyrights
* [ ] The logo should convey the meaning of the "ARNEIS" acronym as described in section "Why the name 'ARNEIS'?" of the [ARNEIS Phase1 proposal](https://github.com/B-AROL-O/opencv-spatial-ai-contest/blob/main/docs/phase1/arneis-proposal-2021-11-20.pdf)
* [ ] The logo should be distinguishable even if reproduced in grayscale, black/white or scaled to 64x64 pixel bitmaps
* [ ] The logo should render beautifully when scaled to the formats required by the following sites and/or apps:
  - [GitHub](https://github.com/)
  - [Twitter](https://twitter.com/)
  - [Telegram](https://web.telegram.org/)
  - [Facebook](https://www.facebook.com/)
  - [Instagram](https://www.instagram.com/)
  - [YouTube](https://www.youtube.com/)
  - [LinkedIn](https://www.linkedin.com/)
  - ... others?

**Comment by gmacario** [comment]
* Suggested font: Arial Light
* Suggested color: TODO (Giallo Paglierino)

**Comment by pitdagosti** [comment]
Hi! Can I help you on creating the logo as I did for B-AROL-O? I have some ideas for ARNEIS too 😄 

Here a sneak peek

![image](https://user-images.githubusercontent.com/90387263/155175749-252b5219-5f90-4f9f-8146-f9813e1f3def.png)

**Comment by gmacario** [comment]
> Hi! Can I help you on creating the logo as I did for B-AROL-O?

That would be awesome @pitdagosti !

> I have some ideas for ARNEIS too 😄
> 
> Here a sneak peek

This is an interesting concept for the overall logo.

Maybe we should restrict a little bit on the choice of colors and/or shades, in order to make sure the logo would be suitable for the social networks listed in the description.

I have also some doubt that the "ARNEIS" text around the oval will have enough contrast against the white background.
But it is only my first feeling, we could see it displayed  - for instance scaling the logo and placing on an Instagram profile.

**Comment by pitdagosti** [comment]
I worked also on this one

![image](https://user-images.githubusercontent.com/90387263/155184332-f868134d-6bc7-4ff9-9c22-d07a7d2f3847.png)

**Comment by pitdagosti** [comment]
I have worked also on this one

![image](https://user-images.githubusercontent.com/90387263/155188424-b96e951e-084d-4fe4-9eec-0d970694f73c.png)

**Comment by alv67** [comment]
I appreciate the second version of the "Text LOGO".

In my opinion can also have some better feel with some litttle aesthetic corrections:
- a little extension of the horizontal center line of the A 
- a connection between R and N by nearing the N and changing a little the R's leg.
- some labels on bottle to give more "bottle feeling" (probably also a thicker border can be an upgrade)

The attached image is only to be used as an explanation of what I means. 
If this idea is approved by the team, then this modifications must be done on the image source.

![155191207-6d3d9e93-76d4-4459-a1b8-20ffcab80d36](https://user-images.githubusercontent.com/25162080/155276695-d3247026-67d6-4901-9640-471dce1e389a.png)

**Comment by gmacario** [comment]
> ![155191207-6d3d9e93-76d4-4459-a1b8-20ffcab80d36](https://user-images.githubusercontent.com/25162080/155276695-d3247026-67d6-4901-9640-471dce1e389a.png)

Let's verify whether the "A" may become a bottle. This might help cropping the logo to make it a square icon

**Comment by alv67** [comment]
![immagine](https://user-images.githubusercontent.com/25162080/155528766-7e1b9e6a-88ed-4655-87e5-7a6bef17cc93.png)

**Comment by pitdagosti** [comment]
Ok I can change the layout of the A, but in order to make it a rectangle overall it will be smaller

**Comment by alv67** [comment]
Rectangle will be done by only keeping a part of the text, I m thinking of using only the A and the connected + removing rneis.
Il 24 feb 2022, 14:51 +0100, pitdagosti ***@***.***>, ha scritto:

**Comment by alv67** [comment]
![logo](https://user-images.githubusercontent.com/25162080/155606188-c424f6e8-ee70-4ea9-ab59-68c0ba699813.png)

**Comment by pitdagosti** [comment]
Ok I'll modify it and send the results!

**Comment by gmacario** [comment]
> Ok I'll modify it and send the results!

Thanks in advance for you PR under docs/images

**Comment by pitdagosti** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/90387263/155743395-32803e00-4fe1-41f9-ac8b-5bfc2eadcc44.png)

**Comment by gmacario** [comment]
The official ARNEIS logo is now available at https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/Arneis_logo_.svg
