### ISSUE TITLE
[FEAT]: ARNEIS LEGO MOC History HD 1080p: Improve text

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#246]
### Description of the bug

There are some imperfections in the text of the video at <https://www.youtube.com/watch?v=ZKtS8KgnbAY>

[![ARNEIS LEGO MOC History HD 1080p](https://img.youtube.com/vi/ZKtS8KgnbAY/0.jpg)](https://www.youtube.com/watch?v=ZKtS8KgnbAY "ARNEIS LEGO MOC History HD 1080p")

### Additional Information

I would suggest to rephrase the text as follows

| Time | Original text | Suggested text
|------:|---------------|------------------
| 0:36 | With real bricks everything is funniest | With real bricks everything is **funnier**
| 0:51 | ... and background for shooting | ... and background for **photo** shooting
| 1:22 | And now build it ... | And now **let's** build it ...
| 1:49 | Now is more than an idea | Now **it** is more than an idea
| 3:01 | The conveyor now seems something useable | Now the conveyor seems **somehow usable**
| 5:10 | ... be see you for next (construction) steps | See you for next (construction) steps...

**Comment by gmacario** [comment]
@alv67 Please Take A Look and let me know if you disagree

**Comment by alv67** [comment]
@gmacario and @gteti this is the new link : https://www.youtube.com/watch?v=S-DiK0UgNBY,
I disable the old one.

**Comment by gmacario** [comment]
> @gmacario and @gteti this is the new link : https://www.youtube.com/watch?v=S-DiK0UgNBY, I disable the old one.

Great, thanks!
