### ISSUE TITLE
[FEAT]: How to export a project from LEGO Powered Up app for iOS?

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#265]
### Description

Page https://github.com/B-AROL-O/ARNEIS/tree/main/code/poweredupapp-flash-move explains how to import a project which has been exported from an Android phone following the instructions at https://racingbrick.com/2020/01/how-to-export-import-a-project-in-the-powered-up-app-on-android/

I am asking some team members who are more knowledgeable than myself on iOS (@alv67 and @gteti I am thinking about you!) if there is a similar procedure which can be applied to the iOS app as well. 

### Additional Information

Rationale: My son Filippo has developed an app on his iPhone and I am too lazy to create it for my Android phone 🤣

**Comment by alv67** [comment]
Sorry, did not find a way to export/reimport the project. 
Officially there is not a way to do this. On Android devices, since there is no a "sandbox" protection of the files of an app, you can browse the file system and get the project file, this is not true for iOS.
