### ISSUE TITLE
Shall we register the ARNEIS logo? 

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#282]
See https://uibm.mise.gov.it/index.php/it/

Rationale:

1. We have [a beautiful logo](https://github.com/B-AROL-O/ARNEIS/pulls?q=is%3Apr+is%3Aclosed+logo) 
2. We (at least, I) am very proud of what we achieved so far
3. We (at least, I) have studied history and do not want to repeat some [mistakes which was done in the past](https://hackaday.com/2016/10/01/arduino-vs-arduino-arduino-won/)

**Comment by gmacario** [comment]
FYI: [This video](https://youtu.be/AqgJ17d8UnQ?t=1660) (from 27:40) could shed some lights on the subject

[![ARDUINO WEEK 2002 Day 6](https://img.youtube.com/vi/AqgJ17d8UnQ/0.jpg)](https://www.youtube.com/watch?v=AqgJ17d8UnQ?t=1660 "ARDUINO WEEK 2002 Day 6")

**Comment by alv67** [comment]
I think that at this real moment spending 510€ to register the logo is a little too much..

See [www.tutelamarchio.com](https://www.tutelamarchio.com/registrare-marchio/registrazione-marchio-nazionale/)

**Comment by gmacario** [comment]
> I think that at this real moment spending 510€ to register the logo is a little too much..
> 
> See [www.tutelamarchio.com](https://www.tutelamarchio.com/registrare-marchio/registrazione-marchio-nazionale/)

How about https://www.proofy.co/ then?

**Comment by alv67** [comment]
In effect proofy can be a valid alternative, with 10€ it's possible to register the logo and store in the their depot for one year.
At the end of this year, you keep in your store the file, but you have the registration certificate.

**Comment by gmacario** [comment]
OK, so based on our conversation let us first make sure we have a signed archive with a sure timestamp (Italian "Data Certa") of at least the following assets:

1. [B-AROL-O](https://github.com/B-AROL-O) logo
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/Barolo_logo_shade.svg
     ![Barolo_logo_shade.svg](https://raw.githubusercontent.com/B-AROL-O/ARNEIS/main/docs/images/Barolo_logo_shade.svg)
3. [ARNEIS](https://github.com/B-AROL-O/ARNEIS) logo in several versions
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/arneis-logo-black-transparent.png
      ![arneis-logo-black-transparent.png](https://github.com/B-AROL-O/ARNEIS/raw/main/docs/images/arneis-logo-black-transparent.png)
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/arneis-logo-black-transparent.png
     ![arneis-logo-black-transparent.png](https://github.com/B-AROL-O/ARNEIS/raw/main/docs/images/arneis-logo-black-transparent.png)
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/arneis-logo-black-transparent.svg
     ![arneis-logo-black-transparent.svg](https://github.com/B-AROL-O/ARNEIS/raw/main/docs/images/arneis-logo-black-transparent.svg)
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/arneis-logo-white-trasparent.png
     ![arneis-logo-white-transparent.png](https://github.com/B-AROL-O/ARNEIS/raw/main/docs/images/arneis-logo-white-transparent.png)
   - https://github.com/B-AROL-O/ARNEIS/blob/main/docs/images/arneis-logo-white-transparent.svg
     ![arneis-logo-white-transparent.svg](https://github.com/B-AROL-O/ARNEIS/raw/main/docs/images/arneis-logo-white-transparent.svg)

[Alessandro](https://github.com/alv67), [Gianluca](https://github.com/gteti) and [Pietro](https://github.com/pitdagosti): Is there anything else you deep registerable (Italian "depositabile")?

Before answering please read and review the following links:

2. <https://uspto.report/TM/79034763>
3. <https://uspto.report/Search/LEGO>
4. <https://uspto.report/TM/85686934>
5. <https://uspto.report/TM/97326847>
6. <https://uspto.report/Search/ARNEIS>
7. <https://uspto.report/Search/Luxonis>

Please advise, thanks

**Comment by gteti** [comment]
For this Item https://uspto.report/Search/Luxonis I think they will register OAK-3, or OAK-S3, based on https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/oak-s3.html

**Comment by gmacario** [comment]
> For this Item https://uspto.report/Search/Luxonis I think they will register OAK-3, or OAK-S3, based on https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/oak-s3.html

Fair enough, but this is unrelated. Please answer to my question at https://github.com/B-AROL-O/ARNEIS/issues/282#issuecomment-1083047909

**Comment by gteti** [comment]
> [Alessandro](https://github.com/alv67), [Gianluca](https://github.com/gteti) and [Pietro](https://github.com/pitdagosti): Is there anything else you deep registerable (Italian "depositabile")?

Maybe "B-AROL-O" ? I don't have anything else.

**Comment by gmacario** [comment]
> Maybe "B-AROL-O" ? I don't have anything else.

Maybe, we should probably consult a specialist to ensure we are not violating previous registrations, for instance <https://uspto.report/TM/79034763> because in this case your registration will be void.

**Comment by gmacario** [comment]
... On the other hand, we could also try to register this name

> **ARNEIS** (short for `A`utomated `R`ecognizer, `N`etwork-`E`nabled, `I`tem Sorter)

**Comment by gmacario** [comment]
> > Maybe "B-AROL-O" ? I don't have anything else.
> 
> Maybe, we should probably consult a professional to ensure we are not violating previous registrations, for instance https://uspto.report/TM/79034763 because in this case our registration will be void.

FYI: I just sent an email asking for legal advices, you are in CC.

**Comment by gmacario** [comment]
@gmacario had a preliminary conf.call with [Interpatent]() where we agreed on the approach and the next steps.
Please refer to the [meeting notes](https://github.com/B-AROL-O/opencv-spatial-ai-contest/tree/main/docs/meeting-notes/2022-04-08-confcall-interpatent) for details

**Comment by gmacario** [comment]
Got feedbacks from the attorney:

> Da: Luisa xxxx <l.xxxx@xxxx.com>
> Date: mer 13 apr 2022 alle ore 12:52
> Subject: Preventivi depositi marchi - Ns. Rif.: Y810IT00
> To: Gianpaolo Macario <gianpaolo.macario@xxxx.it>
> Cc: Pierpaolo xxxx <p.xxxx@xxxx.com>
>
> Buongiorno Ing. Macario,
> ...

@gteti and @alv67 we need to discuss it ASAP. Please let me know when you are available

**Comment by gmacario** [comment]
> In effect proofy can be a valid alternative, with 10€ it's possible to register the logo and store in the their depot for one year. At the end of this year, you keep in your store the file, but you have the registration certificate.

B-AROL-O and ARNEIS logos deposited to Proofy:

<https://app.proofy.co/app/showopera/86955679-eed8-43d8-b2e1-6048355b370b>

![image](https://user-images.githubusercontent.com/75182/167300932-6478ac6e-dbd1-415b-a153-a6460b2ce8be.png)

**Comment by gmacario** [comment]
We eventually decided that for the time being the deposit of B-AROL-O and ARNEIS logos to Proofy was enough and did not proceed with deposit to UIBM or other institutions

https://app.proofy.co/app/showopera/86955679-eed8-43d8-b2e1-6048355b370b
