### ISSUE TITLE
[FEAT]: Configure arneis.readthedocs.io

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#29]
### Description

I have been trying [ReadTheDocs](https://readthedocs.org/).

I followed the tutorial and created a sample site <https://b-arol-o-test-readthedocs.readthedocs.io/en/latest/> based on the contents of <https://github.com/B-AROL-O/test-readthedocs>

I think it would be useful to structure the contents in https://github.com/B-AROL-O/ARNEIS so that the documentation can automagically be rendered under https://arneis.readthedocs.io/en/latest/

**Comment by gteti** [comment]
![immagine](https://user-images.githubusercontent.com/51110452/149628948-1508a267-2d17-4344-ae2c-9c08d1ccc897.png)

Can we use markdown as builder ? So that every document already published is added automatically without needed us to rewrite it.
Otherwise we will need to change all the documents to *.rst and use those as standard for the future.

**Comment by gmacario** [comment]
> Can we use markdown as builder ?

Maybe - <https://www.sphinx-doc.org/en/master/contents.html> has all the answers to this question and others.
More specifically: https://www.sphinx-doc.org/en/master/usage/markdown.html

As you can see I have planned resolution of this task by dev-cw03 but so far there are no assignees...
PR accepted 😉

**Comment by gmacario** [comment]
For starting we could take inspiration from https://github.com/luxonis/depthai-docs-website

**Comment by gmacario** [comment]
See also https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers.html

**Comment by gteti** [comment]
> and https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers.html

This link doesn't seems to work. 
![image](https://user-images.githubusercontent.com/51110452/149887006-23739012-d811-422a-9532-9fab1a9b7442.png)

**Comment by gmacario** [comment]
> > and https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers.html
> 
> This link doesn't seems to work. ![image](https://user-images.githubusercontent.com/51110452/149887006-23739012-d811-422a-9532-9fab1a9b7442.png)

Please try again, I added the link doing copy-and-paste on my mobile and I probably added some garbage in the URL

**Comment by gmacario** [comment]
By the way: @gteti I just assigned myself to this task, so now you must take another one otherwise you will have nothing to do for this week ;-)

**Comment by gteti** [comment]
> By the way: @gteti I just assigned myself to this task, so now you must take another one otherwise you will have nothing to do for this week ;-)

Don't worry. I've assigned myself a long term task. See https://github.com/B-AROL-O/opencv-spatial-ai-contest/issues/132

**Comment by gmacario** [comment]
Initial configuration merged to main,

Let's track improvements in related PR TODO
