### ISSUE TITLE
[FEAT]: Train NN for recognizing mignon bottles

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#31]
### Description

We should train the Neural Network to be executed on the OAK-D-Lite in order to quickly recognize the mignon bottles which will flow through the LEGO conveyor

### Additional Information

Maybe we could try out [Roboflow](https://roboflow.com)?

**Comment by gteti** [comment]
Related to #34 and #47

**Comment by gmacario** [comment]
Just for reference here is a photos of a subset of the mignon bottles currently available for the ARNEIS project:

![Some mignon bottles](https://user-images.githubusercontent.com/75182/146777189-d154dd14-2f70-4097-a950-b17159fdaaf7.jpg)

**Comment by gmacario** [comment]
> Maybe we could try out [Roboflow](https://roboflow.com)?

This task is tracked in a separate issue  (#123)

**Comment by gteti** [comment]
There was an errore with the generate_tfrecord because after I changed the filename of the JPG images, the same was not done inside of the XML files which caused a "missing file" error.

**Comment by gteti** [comment]
I've restarted the training. The whole process restarted from the previous step where it stopped. I set up a 1500 step this time. I hope it completes by tomorrow.

**Comment by gteti** [comment]
The training has been completed with 1500 steps. Running the models test inside the notebook gave the following output.

Miss
![image](https://user-images.githubusercontent.com/51110452/153137667-3f7d3ee2-8c65-48ad-bb22-ac4d870090f6.png)

Correct from behind
![image](https://user-images.githubusercontent.com/51110452/153137729-3b36d225-dfff-40aa-a525-947563ea86c5.png)

Correct from upfront with a bit twist
![image](https://user-images.githubusercontent.com/51110452/153137788-af7c55fe-cd17-4876-96c8-4161e5c36da8.png)

Correct partial view
![image](https://user-images.githubusercontent.com/51110452/153137823-8093fc72-c99c-4ef0-b921-3a2819f1e302.png)

Correct with strange angle and a twist
![image](https://user-images.githubusercontent.com/51110452/153137877-0298aab1-bc32-4fcc-8cdb-f142f7b45c60.png)

**Comment by gteti** [comment]
I've written at https://github.com/B-AROL-O/ARNEIS/issues/53 
> Network usefull for objects detection:
> 
>     MobileNet: Detects the dominant objects present in an image
>     Inception v3: Detects the dominant objects present in an image (224x224)
>     ResNet50: Detects the dominant objects present in an image
>     VGG16: Detects the dominant objects present in an image (224x224)
>     YOLO: Recognize what the objects are inside a given image and where they are
> 
> (side note if it might be usefull DepthPrediction: predict the depth from a single image)

**Comment by gteti** [comment]
I've discovered Tensorboard and used it, through the notebook, to train the network for 7000
![image](https://user-images.githubusercontent.com/51110452/154484234-aac8b71b-2d76-42bf-955d-c42d00544ff8.png)
