### ISSUE TITLE
[FEAT]: Understand which existing demo(s) we can leverage to develop ARNEIS code

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#34]
### Description

Before even attempting to develop new code for the ARNEIS project we should have a broad look at the existing demos and example code already available in the public:

- Repository with sources: https://github.com/luxonis/depthai
- Please see also: https://github.com/luxonis/depthai-experiments

**Comment by gmacario** [comment]
@gteti beyond the Out-of-the-box DepthAI demo <https://github.com/luxonis/depthai/blob/main/depthai_demo.py> did you find any additional programs or code we could start from?

Please comment, otherwise we may close the issue for the moment

**Comment by gteti** [comment]
As I mentioned I'm still learning and finishing the basic FreeOpenCV course. Everything explained there might be useful but if I don't finish this and start learning DepthAI, I can't look for anything else yet.

**Comment by gmacario** [comment]
> As I mentioned I'm still learning and finishing the basic FreeOpenCV course. Everything explained there might be useful but if I don't finish this and start learning DepthAI, I can't look for anything else yet.

That makes sense, let's replan in two weeks, then. Thanks

**Comment by gmacario** [comment]
In the meanwhile I am also adding the "help wanted" label - I have the idea to ask guidance on Discord

**Comment by gteti** [comment]
I've finished the OpenCV free course. I'll start with DepthAI by tomorrow.

**Comment by gteti** [comment]
Important link https://docs.luxonis.com/projects/api/en/latest/tutorials/hello_world/

**Comment by gteti** [comment]
Testing the notebooks on Google colab
https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_Object_Detection_With_Custom_Data_Demo_Training.ipynb

**Comment by gteti** [comment]
I have understood that the notebook can be used for our usecase.
