### ISSUE TITLE
[BUG]: README.md: Video not available

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#345]
### Description of the bug

From the top-level README.md:

> A 5-min video summarizing the history of the ARNEIS project is [available on YouTube](https://www.youtube.com/watch?v=ZKtS8KgnbAY).

But when I click on the link I get:

![image](https://github.com/B-AROL-O/ARNEIS/assets/75182/2df09dae-82c3-4d1f-83f4-cdab423a8ac4)

### Steps To Reproduce

1. Go to https://github.com/B-AROL-O/ARNEIS
2. In section "The Timeline", click on https://www.youtube.com/watch?v=ZKtS8KgnbAY
3. Read the error message

### Additional Information

Tested from the LinkedIn app running on my Huawei Mate 10 PRO mobile phone (Android 12)

Also reproduced on Google Chrome 115.0.5790.110 running on ALPHA (OS: Windows 10 Pro)

**Comment by gmacario** [comment]
@alv67 have you deleted or moved the YouTube video which was referenced from the toplevel README.md?

```text
A 5-min video summarizing the history of the ARNEIS project is
[available on YouTube](https://www.youtube.com/watch?v=ZKtS8KgnbAY).
```

**Comment by alv67** [comment]
I keeped public only the official last version of the video : https://youtu.be/qHFRRHWtTqY 

Sorry.

**Comment by gmacario** [comment]
> I keeped public only the official last version of the video : https://youtu.be/qHFRRHWtTqY
> 
> Sorry.

No problems. Would you mind submitting a PR which fixes the bug with a link to an existing video instead?
