### ISSUE TITLE
[FEAT]: Enhancements to B-AROL-O logo

### ISSUE THREAD

**Issue by pitdagosti** [B-AROL-O/ARNEIS#35]
### Description

Hi! I would like to enhance your logo since there are some details that can be improved :smile:

In these days I will provide you the results! Here what I would like to modify:

* Make the curve simmetrical on both edges
* The B should be put in the middle of the image which I've tried to understand by drawing a line in the middle of the gear. So maybe it should go like some millimeters/pixels down.
* Change the bottom layout

![image](https://user-images.githubusercontent.com/90387263/149653682-b96e0347-3d40-433e-9ea5-eddaa84e0d37.png)

**Comment by gmacario** [comment]
Thanks for your proposal @pitdagosti!

If you are able to do what you propose and have already studied for your next exams I encourage you to do so and submit a PR here :-)

**Comment by gteti** [comment]
Thank you for your help! Let us know what we can do to help you out.

**Comment by gmacario** [comment]
Updated B-AROL-O logo uploaded to

* GitHub: https://github.com/B-AROL-O
* Twitter: https://twitter.com/baroloteam
