### ISSUE TITLE
[FEAT]: Link video recording of the B-AROL-O Team interview at the 2023-06-17 MS AI Show

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#355]
### Description

Event and date: [The AI Show with Seth Juarez](https://aka.ms/AIShowLive) on Friday, June 17th, 2022, at 11:00am Pacific.

* [x] Embed YouTube video in toplevel README.md
* [x] Add link in page docs/arneis_social_media.md

**Comment by AndreaPodo** [comment]
You can find it here:
<https://www.youtube.com/watch?v=cl1sDvzCD9c&ab_channel=SethJuarez>
