### ISSUE TITLE
[FEAT]:  Submit ARNEIS project final report to OpenCV contest

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#42]
### Description

This is a reminder that in order to qualify for Phase 2 of the [OpenCV Spatial AI Contest](https://opencv.org/opencv-spatial-ai-contest/) we should submit the final report on time

> Finalists will have from January 1st until **April 4st 2022 at 11:59pm PST** to complete their projects and submit final reports.

### Additional Information

Excerpt from the [email received on 2022-03-14](https://ckarchive.com/b/8kuqhoh4qp8k)

> The **Final Project Submission PDF** should include
> * your **team roster and background**, as well as
> * a **summary of your project** from the beginning ideas to the final version you are submitting.
>
> Include specific details about
> * **challenges you overcame** during the build phase,
> * **how/if you used tools** like Azure and OpenVINO, and please
> * link to any **webpage or social media content** you created.

**Comment by gmacario** [comment]
Final submission uploaded to TODO, closing

**Comment by gteti** [comment]
I've updated some parts. Please use the latest for submission.

**Comment by gmacario** [comment]
> I've updated some parts. Please use the latest for submission.

Trying again...

![image](https://user-images.githubusercontent.com/75182/161793889-fe3bff1d-8744-49d6-9df9-e2a68baf3c37.png)
