### ISSUE TITLE
Learn DepthAI focusing on what the OAK-D-LITE can do

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#47]

**Comment by gteti** [comment]
Wrong project to open the Issue.

**Comment by gteti** [comment]
What I learned this week is being written in #58

**Comment by gmacario** [comment]
Keeping issue open, moving to dev-cw04

**Comment by gmacario** [comment]
Keeping it open and extending to next sprint

**Comment by gteti** [comment]
Will close for now.
