### ISSUE TITLE
[FEAT]: Check Model Zoo(s)

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#53]
### Description

Closely related to https://github.com/B-AROL-O/ARNEIS/issues/34 we should check a few catalogs of existing AI models to find any which

1. Can be suitable or leveraged for the ARNEIS use cases
2. Can be deployed on the OAK-D-Lite

### Additional Information

A (non exhaustive) list of sites to check:

* https://zoo.luxonis.com/
* https://github.com/openvinotoolkit/open_model_zoo

**Comment by gteti** [comment]
We may need to use a generic model (maybe one already used to detect bottles) and train that with our samples.

**Comment by gteti** [comment]
To train a neural network we will need to use https://github.com/luxonis/depthai-ml-training

**Comment by gmacario** [comment]
@

> To train a neural network we will need to use https://github.com/luxonis/depthai-ml-training

Did you notice the advice at the beginning of  README.md

> We at Luxonis encourage our users to try out [RoboFlow](https://roboflow.com/) for annotating, training and deploying their ML models, especially if you are new to the ML world.

**Comment by gteti** [comment]
This might come in handy https://github.com/PINTO0309/PINTO_model_zoo

**Comment by gteti** [comment]
> @gteti
> 
> > To train a neural network we will need to use https://github.com/luxonis/depthai-ml-training
> 
> Did you notice the advice at the beginning of README.md
> 
> > We at Luxonis encourage our users to try out [RoboFlow](https://roboflow.com/) for annotating, training and deploying their ML models, especially if you are new to the ML world.

I'll look into it.

**Comment by gmacario** [comment]
See also: https://learnopencv.com/top-10-sources-to-find-computer-vision-and-ai-models/

**Comment by gteti** [comment]
Network usefull for objects detection:
- MobileNet: Detects the dominant objects present in an image
- Inception v3: Detects the dominant objects present in an image
- ResNet50: Detects the dominant objects present in an image
- VGG16: Detects the dominant objects present in an image
- YOLO: Recognize what the objects are inside a given image and where they are

(side note if it might be usefull DepthPrediction: predict the depth from a single image)
