### ISSUE TITLE
[FEAT]: Investigate the feasibility to use 2 OAK-D-Lites at the same time

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#54]
### Description

We might need (in the far future) to use 2 OAK-D-LITE at the same time to cover more perfect detection of the bottles.

**Comment by gteti** [comment]
@gmacario Can you please bring your OAK-D-LITE ? I want to test if the code developed works.

**Comment by gmacario** [comment]
> @gmacario Can you please bring your OAK-D-LITE ? I want to test if the code developed works.
> 
> If you want a photo for the weekly post, you may need to bring a mini bottle JUST FOR SHOW.

Sure I will, and will also bring [this other gadget](https://github.com/B-AROL-O/ARNEIS/issues/55#issuecomment-1015869050)

**Comment by gteti** [comment]
The developed code works for 1 OAK-D
![image](https://user-images.githubusercontent.com/51110452/150115668-3c76d47f-8f43-465a-bb05-39194ef20909.png)

When 2 OAK-D-LITE are connected to the same computer, the software start, displays the 2 frames and then crashes.

**Comment by gmacario** [comment]
> The developed code works for 1 OAK-D ![image](https://user-images.githubusercontent.com/51110452/150115668-3c76d47f-8f43-465a-bb05-39194ef20909.png)
> 
> When 2 OAK-D-LITE are connected to the same computer, the software start, displays the 2 frames and then crashes.

I would recommend to publish the source code as-is under a proper subdirectory (for instance, /code/xxx) of https://github.com/B-AROL-O/ARNEIS, then add some more contest to this issue and ask for help on a Discord channel of luxonis. Maybe they can help out sorting this issue quickly

**Comment by gteti** [comment]
After the fix proposed https://github.com/luxonis/depthai-experiments/issues/280
the code seems to work fine now and it is already present in a PR #58 . 

![image](https://user-images.githubusercontent.com/51110452/150532594-03f9fa24-a597-49f4-8309-df9b70ca1e00.png)
