### ISSUE TITLE
[FEAT]: Investigate camera lighting

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#55]
### Description

I believe we should carefully select how to provide lighting in order to take the best performances out of the excellent OAK-D-Lites [we have been gifted by the OpenCV Spatial AI Contest organizers](https://twitter.com/gpmacario/status/1480612900502917122).

![photo of our OAK-D-Lites](https://pbs.twimg.com/media/FIwvtzLXwAgVci6?format=jpg&name=small)

This task has the goal of collecting suggestions rom friends and colleagues, best practices and experiences with past projects, etc.

**Comment by gmacario** [comment]
FTR: A few weeks ago I made a *huge* company investment and purchased [the following device](https://www.amazon.it/gp/product/B07K9M9V1D) from Amazon.it

![image](https://user-images.githubusercontent.com/75182/150024678-b46628f1-7c9e-4ed7-a846-e4d8085e54d3.png)

Since the last possible day of return is 2022-01-31 tonight I tested it and it seems to work pretty well.

If anyone wants to have a look at it, just let me know and I can lend it to you for a few days

**Comment by gteti** [comment]
> FTR: A few weeks ago I made a _huge_ company investment and purchased [the following device](https://www.amazon.it/gp/product/B07K9M9V1D) from Amazon.it
> 
> ![image](https://user-images.githubusercontent.com/75182/150024678-b46628f1-7c9e-4ed7-a846-e4d8085e54d3.png)
> 
> Since the last possible day of return is 2022-01-31, I tested my impulse purchase tonight and it seems to work pretty well.
> 
> If anyone wants to have a look at it, just let me know and I can lend it to you for a few days

For now the training with the images taken with the camera + light we had, was enough. We will investigate further when the system integration with the conveyor will take place.
