### ISSUE TITLE
Is 64-bit version of the Raspberry Pi OS officially supported?

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#6]

**Comment by gteti** [comment]
Did they release a 64-bit version of the Raspbian OS ? I always thought it was a 32-bit version.

**Comment by gmacario** [comment]
According to https://www.tomshardware.com/news/raspberry-pi-os-bullseye-released (dated 2021-11-08)

> The new Raspberry Pi OS is still based upon a 32-bit release, but it appears that there is also a 64-bit release,
> lurking in the shadows and [spotted by Geerling](https://twitter.com/geerlingguy/status/1457688726755233803).
> Whether this is still a beta or ready for release remains uncertain.

**Comment by gmacario** [comment]
As a matter of fact, the 64-bit version of the Raspberry Pi OS is available in beta since 2020-05-28: <https://forums.raspberrypi.com/viewtopic.php?t=275370>

According to this [2020-11-16 post by one Raspberry Pi Engineer](https://forums.raspberrypi.com/viewtopic.php?t=275370#p1761738)

> Latest builds of the 64 bit image can be found
>
> <https://downloads.raspberrypi.org/raspios_arm64/images/>
>
> Contains changes in line with the 32bit version, still no hardware accelerated Chromium or VLC.

**Comment by gmacario** [comment]
Again according to this [2021-11-08 tweet by Jeff Geerling](https://twitter.com/geerlingguy/status/1457826920725467146)

>> I seem to have broken my Pi while trying to upgrade to Bullseye.
>> Do you think that the 64bit build is sufficiently stable for regular usage?
>
> Yes, though some things don't work, like camera interfaces.
>
> For all server stuff I do, 64-bit's been rock solid.

**Comment by gmacario** [comment]
Based on the information available so far I would propose to keep using the 32-bit (default) version of Raspberry Pi OS for the ARNEIS project so we have hardware acceleration on Chromium and VLC. Also the 32-bit version still works on older or smaller versions of RPi such as the RPi Zero.

Anyway if time permits it would be interesting to try running the code on a 64-bit version of the OS - maybe in the server (lite) version.

Closing #6, and tracking this further activity in #8
