### ISSUE TITLE
[FEAT]: READTHEDOCS display TOC

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#66]
### Description

I've seen our page https://arneis.readthedocs.io/en/latest/  not displaying the correct TOC.

### Additional Information

The official READTHEDOCS documentation has some issues and is not working properly (see https://readthedocs.org/projects/auto-table-of-content/badge/ ) so I went to google and found out : https://sublime-and-sphinx-guide.readthedocs.io/en/latest/snippets.html#use-snippets-as-shortcuts

Maybe we can try this too and see if it helps.

**Index Page TOC**
```
<snippet>
  <content><![CDATA[
.. toctree::
    :maxdepth: 1

      file
      file
      file
      file
]]></content>
  <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
  <tabTrigger>toc</tabTrigger>
</snippet>
```

**Comment by gmacario** [comment]
> I've seen our page https://arneis.readthedocs.io/en/latest/ not displaying the correct TOC.

@gteti please check now on https://arneis.readthedocs.io/en/latest/ - I believe that now the ToC is correct:

![image](https://user-images.githubusercontent.com/75182/151165801-0a157c18-10d4-419f-bd1e-7f6589a0c5cc.png)

Please close if you agree, or comment specifying what is missing or wrong.
Thanks
