### ISSUE TITLE
[BUG]: Build of project ARNEIS on readthedocs.org fails

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#68]
### Description of the bug

As shown in https://readthedocs.org/projects/arneis/builds/

![image](https://user-images.githubusercontent.com/75182/150436281-0eb231cd-a026-42cb-a127-b2b6cdc2700a.png)

### Steps To Reproduce

1. Go to https://readthedocs.org/projects/arneis/builds/
2. Verify that Recent Builds are marked
   > Failed version latest (html)
3. Click on most recent failed build to undestand what was going wrong

**Comment by gmacario** [comment]
As shown in https://readthedocs.org/projects/arneis/builds/15823551/

Failing command:

```bash
/home/docs/checkouts/readthedocs.org/user_builds/arneis/envs/latest/bin/python \
    -m pip \
    install \
    --exists-action=w \
    --no-cache-dir \
    -r docs/requirements.txt
```

Result:

```text
Collecting aiofiles==0.6.0
  Downloading aiofiles-0.6.0-py3-none-any.whl (11 kB)
Collecting ajsonrpc==1.1.0
  Downloading ajsonrpc-1.1.0-py3-none-any.whl (22 kB)
Requirement already satisfied: alabaster==0.7.12 in /home/docs/checkouts/readthedocs.org/user_builds/arneis/envs/latest/lib/python3.7/site-packages (from -r docs/requirements.txt (line 3)) (0.7.12)
Collecting appdirs==1.4.3
  Downloading appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting attrs==19.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting Automat==0.8.0
  Downloading Automat-0.8.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: Babel==2.9.1 in /home/docs/checkouts/readthedocs.org/user_builds/arneis/envs/latest/lib/python3.7/site-packages (from -r docs/requirements.txt (line 7)) (2.9.1)
Collecting bcj-cffi==0.5.1
  Downloading bcj_cffi-0.5.1-cp37-cp37m-manylinux2014_x86_64.whl (36 kB)
Collecting blinker==1.4
  Downloading blinker-1.4.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting bottle==0.12.19
  Downloading bottle-0.12.19-py3-none-any.whl (89 kB)
Collecting Brotli==1.0.9
  Downloading Brotli-1.0.9-cp37-cp37m-manylinux1_x86_64.whl (357 kB)
Collecting certifi==2019.11.28
  Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting cffi==1.14.6
  Downloading cffi-1.14.6-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click==8.0.1
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
Collecting colorama==0.4.3
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
ERROR: Could not find a version that satisfies the requirement command-not-found==0.3 (from versions: none)
ERROR: No matching distribution found for command-not-found==0.3
```

**Comment by gmacario** [comment]
According to https://readthedocs.org/projects/arneis/builds/15823551/ readthedocs.org try to perform the build with python3.7
while local build was successful on gmpowerhorse using Python 2.7

```bash
cd docs/
PATH=$HOME/.local/bin:$PATH
make html
python --version
```

Result:

```text
gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ make html
/bin/sh: 1: sphinx-build: not found
make: *** [Makefile:20: html] Error 127
gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ PATH=$HOME/.local/bin:$PATH
gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ make html
Running Sphinx v4.4.0
loading pickled environment... done
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] requirements                                  
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-configure-arneis-readthedocs-io.md: WARNING: document isn't included in any toctree
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md: WARNING: document isn't included in any toctree
/home/gmacario/github/B-AROL-O/ARNEIS/docs/requirements.txt: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] requirements                                   
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:33: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:45: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:45: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:57: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:81: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:81: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:99: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:99: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:118: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:118: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:133: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:133: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:181: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
/home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
generating indices... genindex done
writing additional pages... search done
copying images... [100%] images/2022-01-13-1736-vnc-connect-rpi4gm35.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 28 warnings.

The HTML pages are in _build/html.
gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ python --version
Python 2.7.18
gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$
```

**Comment by gmacario** [comment]
Tested on kali VM at https://tryhackme.com/

Commands:

```bash
mkdir -p $HOME/github/B-AROL-O
cd $HOME/github/B-AROL-O
git clone https://github.com/B-AROL-O/ARNEIS
cd ARNEIS
git checkout -b test/issue-68
python3.7 --version
```

Result:

```text
root@kali:~/github/B-AROL-O/ARNEIS# python3 --version
Python 3.9.9
root@kali:~/github/B-AROL-O/ARNEIS# 
```

Commands:

```bash
python3.7 -m venv .venv
source .venv/bin/activate
python --version
pip --version
```

Result:

```text
root@kali:~/github/B-AROL-O/ARNEIS# python3 -m venv .venv
root@kali:~/github/B-AROL-O/ARNEIS# source .venv/bin/activate
(.venv) root@kali:~/github/B-AROL-O/ARNEIS# python --version
Python 3.9.9
(.venv) root@kali:~/github/B-AROL-O/ARNEIS# pip --version
pip 20.0.2 from /root/github/B-AROL-O/ARNEIS/.venv/lib/python3.9/site-packages/pip (python 3.9)
(.venv) root@kali:~/github/B-AROL-O/ARNEIS#
```

Type the following commands inside a .venv shell:

```bash
TODO
```

Result:

```text
TODO
```

**Comment by gmacario** [comment]
Recreating docs/requirements.txt

TODO

**Comment by gteti** [comment]
> According to https://readthedocs.org/projects/arneis/builds/15823551/ readthedocs.org tried to perform the failed build using python3.7 while a local build was successful on gmpowerhorse using Python 2.7
> 
> ```shell
> cd docs/
> PATH=$HOME/.local/bin:$PATH
> make html
> python --version
> ```
> 
> Result:
> 
> ```
> gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ make html
> /bin/sh: 1: sphinx-build: not found
> make: *** [Makefile:20: html] Error 127
> gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ PATH=$HOME/.local/bin:$PATH
> gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ make html
> Running Sphinx v4.4.0
> loading pickled environment... done
> myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 3 source files that are out of date
> updating environment: 0 added, 3 changed, 0 removed
> reading sources... [100%] requirements                                  
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-configure-arneis-readthedocs-io.md: WARNING: document isn't included in any toctree
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md: WARNING: document isn't included in any toctree
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/requirements.txt: WARNING: document isn't included in any toctree
> done
> preparing documents... done
> writing output... [100%] requirements                                   
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:33: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:45: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:45: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:57: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:81: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:81: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:99: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:99: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:118: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:118: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:133: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:133: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:145: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:160: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:171: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:181: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
> /home/gmacario/github/B-AROL-O/ARNEIS/docs/howto/howto-prepare-rpi4b-for-arneis.md:194: WARNING: 'myst' reference target not found: TODO
> generating indices... genindex done
> writing additional pages... search done
> copying images... [100%] images/2022-01-13-1736-vnc-connect-rpi4gm35.png
> copying static files... done
> copying extra files... done
> dumping search index in English (code: en)... done
> dumping object inventory... done
> build succeeded, 28 warnings.
> 
> The HTML pages are in _build/html.
> gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$ python --version
> Python 2.7.18
> gmacario@gmpowerhorse:~/github/B-AROL-O/ARNEIS/docs (main)$
> ```
> 
> TODO: Try a local build on a different host (i.e. rpi4gm45)

Remember that on Ubuntu machines you may have `python` command which runs python 2.X.T while `python3` command that uses python 3.Y.Z
