### ISSUE TITLE
Wait for delivery of the requested LEGO set

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#7]
From 2022-01-07 mail from OpenCV Competition:

> On a less awesome note, LEGO fulfillment is proving problematic due to the holidays and global supply chain issues.
> Teams in the United States of America, Germany, Canada, and the United Kingdom will receive LEGO.com e-gift cards via email.
> Unfortunately LEGO does not offer these cards worldwide.
> For all other teams we're working on locating and shipping the kits as you specified in the Finalist Form.
> An OpenCV team member will contact you directly via email about your team's LEGO kits within the next few days.
> Thanks for your patience.

**Comment by gmacario** [comment]
Da: Phil Nelson <phil@*****.org>
Date: lun 17 gen 2022 alle ore 19:48
Subject: Your OpenCV Spatial AI Contest LEGO Sets
To: <gmacario@*****.com>

Gianpaolo,

The sets you’ve entered in the form:

"LEGO® Powered UP: Escavatore Liebherr R 9800 (42100): https://www.zavvi.it/toys-lego/lego-powered-up-escavatore-liebherr-r-9800-42100/12041888.html

42121 LEGO® TECHNIC Escavatore idraulico: https://www.manomano.it/catalogue/p/42121-lego-technic-escavatore-idraulico-41017400"

 are above the $400 USD budget for the contest- you’ll need to modify your choices in order for us to send.

Thanks,
Phil Nelson
phil@*****.org
Content Manager, OpenCV.org

**Comment by gmacario** [comment]
Da: Gianpaolo Macario <gmacario@xxxxx.com>
Date: mar 18 gen 2022 alle ore 08:01
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Phil Nelson <phil@xxxxx.org>
Cc: Alessandro Varesi <xxxxx@xxxxx.com>, Gianluca Teti <xxxxx@xxxxx.com>

Good morning Phil,

Il giorno lun 17 gen 2022 alle ore 19:48 Phil Nelson <phil@xxxxx.org> ha scritto:

> Gianpaolo,
>
> The sets you’ve entered in the form:
>
> "LEGO® Powered UP: Escavatore Liebherr R 9800 (42100): https://www.zavvi.it/toys-lego/lego-powered-up-escavatore-liebherr-r-9800-42100/12041888.html
>
> 42121 LEGO® TECHNIC Escavatore idraulico: https://www.manomano.it/catalogue/p/42121-lego-technic-escavatore-idraulico-41017400"
>
> are above the $400 USD budget for the contest- you’ll need to modify your choices in order for us to send.

As a matter of fact the price of the two sets was less than 400$ when I submitted the form a few weeks ago.

Anyway I have just checked https://www.zavvi.it/toys-lego/lego-powered-up-escavatore-liebherr-r-9800-42100/12041888.html
and it states "309,99 EUR" which is way less 400 $ including shipping.

If adding the second set is out of budget please order and have only this set delivered to us before it becomes again out of stock.

To expedite reception please also have the packet delivered to Alessandro home address instead of the original address which I specify in the order:

> Alessandro Varesi
> via xxxxx xxxxx, xxxxx
> xxxxx xxxxx TO
> Italy

image.png

> Thanks,
> Phil Nelson
> phil@xxxxx.org
> Content Manager, OpenCV.org

Best regards,

--
Gianpaolo Macario
gmacario@xxxxx.com

**Comment by gmacario** [comment]
Da: Phil Nelson <phil@xxxx.org>
Date: ven 28 gen 2022 alle ore 21:16
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Gianpaolo Macario <gmacario@xxxx.com>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>


Gianpaolo,

I’ve been trying to track this down online for awhile, it appears the Liebherr R 9800 Excavator set is retired by LEGO. Is there any other way you can think of to acquire this set, and we will reimburse you via PayPal?

Phil Nelson
phil@xxxx.org
Content Manager, OpenCV.org

**Comment by gmacario** [comment]
Da: Gianpaolo Macario <gmacario@xxxx.com>
Date: sab 29 gen 2022 alle ore 09:10
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Phil Nelson <phil@xxxx.org>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>

Hello Phil,

>  I’ve been trying to track this down online for awhile, it appears the Liebherr R 9800 Excavator set is retired by LEGO.

That's a sad piece of information.

As a matter of fact we have been working for the last couple of months with the assumption that we would receive LEGO Set 42100 by the OpenCV Spatial AI Contest organization.

When I submitted the confirmation form for Phase 2 on 2021-12-20 the LEGO set was available from https://www.zavvi.it/toys-lego/lego-powered-up-escavatore-liebherr-r-9800-42100/12041888.html

We have already developed some concepts on CAD, as you can see https://twitter.com/avaresi/status/1486027840533499904

Now we badly need this set, otherwise we will not be able to progress on the project :-(

I just made a quick check and it looks like the set is still available (although at a much higher price than the one I reported in December) from a couple of vendors on Amazon.it:

image.png

and eBay.it

image.png

but there are very few items available, so we need to hurry up.

> Is there any other way you can think of to acquire this set, and we will reimburse you via PayPal?

The only idea we had together with the other B-AROL-O team members is the following:

1. You pay 400$ in advance to my PayPal account (gmacario@xxxx.com)
2. As soon as I receive the payment, we will try to find a LEGO 42100 set available on Amazon or eBay and purchase it. In case the set will cost more than 400$ (as it is expected since prices for discontinued sets are usually growing) we commit to add the extra money on our expense
3. We will send a picture of the set together with ourselves as a proof of the purchase.  

Would this work out for the OpenCV Spatial AI Contest rules?

**Comment by gmacario** [comment]
Da: Phil Nelson <phil@xxxx.org>
Date: sab 29 gen 2022 alle ore 18:15
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Gianpaolo Macario <gmacario@xxxx.com>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>

Gianpaolo,

Your solution is more than fair since we were unable to acquire the set in time. We will send the payment on Monday to your PayPal.

Phil Nelson
phil@xxxx.org
Content Manager, OpenCV.org

**Comment by gmacario** [comment]
Spamming on Twitter about B-AROL-O looking for one [LEGO Set 42100](https://www.lego.com/en-it/product/liebherr-r-9800-excavator-42100)

* https://twitter.com/baroloteam/status/1487778753027715073

   ![image](https://user-images.githubusercontent.com/75182/151701821-1c7b0ff7-60c4-4f83-8186-83cea11cb9d4.png)

then quote tweeted by @gmacario

* https://twitter.com/gpmacario/status/1487779578118615044

   ![image](https://user-images.githubusercontent.com/75182/151701848-2fe0557a-0484-4ff8-a9c7-65d7656d884e.png)

**Comment by gteti** [comment]
:D :D Just for appearences, right ??

**Comment by gteti** [comment]
Let's hope we find one!

**Comment by gmacario** [comment]
Da: Gianpaolo Macario <[gmacario@gmail.com](mailto:gmacario@xxxx.com)>
Date: mer 2 feb 2022 alle ore 08:52
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Phil Nelson <phil@xxxx.org>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>

Hello Phil,

> I had some issues accessing our PayPal on Monday, but it is resolved.
> You should see the money arrive today.

I just checked on my PayPal account (gmacario@xxxx.com) and the transaction is not yet recorded.
Anyway I will check again tomorrow and let you know.

> Once you buy the kit, I’ll need the receipt as well for our records.

OK. We have identified a best deal of a used set (370 EUR + 5,49 EUR shipping) from
https://www.subito.it/hobby-collezionismo/lego-vari-aosta-420440244.htm
but this is probably from a private individual, not a firm, so we are unsure this will be OK for you.
Could you please check and let us know?

Alternatively there are a few deals on Amazon.it and eBay.it but they are much more expensive.

...

Thanks -- Gianpaolo

**Comment by gmacario** [comment]
Da: Phil Nelson <phil@xxxx.org>
Date: mer 2 feb 2022 alle ore 21:43
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Gianpaolo Macario <gmacario@xxxx.com>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>

Gianpaolo,

Just confirmed the money was sent a few moments ago from [accounting@xxxx.org](mailto:accounting@xxxx.org) to you. Hopefully this will make it easier to get your gear and make your project great. 

...

Phil Nelson
[phil@xxxx.org](mailto:phil@xxxx.org)
Content Manager, [OpenCV.org](http://opencv.org/)

**Comment by gmacario** [comment]
Da: Gianpaolo Macario <gmacario@xxxx.com>
Date: gio 3 feb 2022 alle ore 12:21
Subject: Re: Your OpenCV Spatial AI Contest LEGO Sets
To: Phil Nelson <[phil@opencv.org](mailto:phil@xxxx.org)>
Cc: Alessandro Varesi <avaresi@xxxx.com>, Gianluca Teti <gianluca.teti@xxxx.com>

Hello Phil,

Please find my comments inline.

Il giorno mer 2 feb 2022 alle ore 21:43 Phil Nelson <phil@xxxx.org> ha scritto:

> Gianpaolo,

>
> Just confirmed the money was sent a few moments ago from [accounting@xxxx.org](mailto:accounting@xxxx.org) to you.

I confirm I just received the money on my PayPal account. Thanks!

TODO:image.png

We are now going to purchase one set from the current offers and will mail you back the receipt as soon as possible.
 
> 
Hopefully this will make it easier to get your gear and make your project great.

Indeed!
 
...

--
Gianpaolo Macario
[gmacario@xxxx.com](mailto:gmacario@xxxx.com)

**Comment by gmacario** [comment]
@alv67, @gteti (and/or anyone else who is watching this thread): Please comment with the cheapest deal you have found on Amazon.it and/or eBay.it which is still available.

Make sure we can get the receipts which are required by OpenCV.

Tomorrow morning I will issue the purchase order

**Comment by alv67** [comment]
I sent one yesterday on telegram. Need to contac seller to check if a receipt is given.

Inviato da iPhone

**Comment by gteti** [comment]
> I sent one yesterday on telegram. Need to contac seller to check if a receipt is given. Inviato da iPhone
> […](#)
> Il giorno 3 feb 2022, alle ore 18:14, Gianpaolo Macario ***@***.***> ha scritto: ﻿ @alv67, @gteti (and/or anyone else who is watching this thread): Please comment with the cheapest deal you have found on Amazon.it and/or eBay.it which is still available. Make sure we can get the receipts which are required by OpenCV. Tomorrow morning I will issue the purchase order — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

That one is now no more available on that website. I've also posted some today.

**Comment by alv67** [comment]
Wow, when I found it there where 6 items and today no one. The speed of selling this set is astonishing.
Il 3 feb 2022, 20:46 +0100, Gianluca Teti ***@***.***>, ha scritto:

**Comment by gmacario** [comment]
Issued Purchase Order on eBay

![image](https://user-images.githubusercontent.com/75182/152485951-41a42cb3-6789-448b-a4ea-428224c58731.png)

**Comment by gmacario** [comment]
Unfortunately our order was canceled by the supplier who discovered that the item was faulty.

@alv67 will take care of finding an alternate supplier ASAP:

**Comment by alv67** [comment]
Cross the finger 🤞, placed an Amazon order from a German seller. Suppose to receive the set on monday 14.

Need to invest some more money but it is a very good price in this moment.

<img width="928" alt="Dettagli ordine - cleaned" src="https://user-images.githubusercontent.com/25162080/153680313-25556539-7ed7-4983-b4f8-3877ee1c78eb.png">

Hope to have good news on monday! As soon as received I will post here some photos.

**Comment by alv67** [comment]
# Finally we have the LEGO set

Attached the last two mail that closes this task

---------- Forwarded message ---------
Da: Phil Nelson <[phil@opencv.org](mailto:phil@opencv.org)>
Date: lun 14 feb 2022 alle ore 19:35
Subject: Re: The quest for the LEGO set is over!
To: Alessandro Varesi <avaresi@gmail.com>
Cc: Gianpaolo Macario <gmacario@gmail.com>, #WRK TETI Gianluca <gianluca.teti@gmail.com>


Hooray! Thank you. Always a fan of banana for scale 🤣

Phil Nelson
phil@opencv.org
Content Manager, [OpenCV.org](http://opencv.org/)

---------- Forwarded message ---------
Da: Alessandro Varesi <avaresi@gmail.com>
Date: lun 14 feb 2022 alle ore 18:56
Subject: The quest for the LEGO set is over!
To: Phil Nelson <phil@opencv.org>
Cc: Gianpaolo Macario <gmacario@gmail.com>, #WRK TETI Gianluca <gianluca.teti@gmail.com>


Hi Phil,

(and team friends)

The LEGO set is here.

We spent a little more than expected, but finally the research is completed.

Attached you find a picture of the box ( 🍌 for scale) and my Amazon receipt (omissis).

Please consider the receipt as CONFIDENTIAL since it contains my personal home address.

Starting now I’ll do my best to build something to show on thursday.


Alessandro Varesi (@alv67)
![LEGO 42100 (banana for scale)](https://user-images.githubusercontent.com/25162080/154041966-18c4a11b-e9ad-4281-bcf3-08c5b9c8b115.jpeg)
