### ISSUE TITLE
[FEAT]: main branch protection

### ISSUE THREAD

**Issue by alv67** [B-AROL-O/ARNEIS#74]
### Description

Protect `main` branch from direct modification. Only merging pull request can modify the main branch. 

In repository setting set protection to the `main` branch. 

![immagine](https://user-images.githubusercontent.com/25162080/150484398-2cbb8c3d-8b6e-489d-a65e-a0d70dc31557.png)

**Comment by gmacario** [comment]
Done, @alv67 please check and close if OK.

I was also tempted to enable the following 

![image](https://user-images.githubusercontent.com/75182/150573804-dd15ccb0-fbf5-4a41-89b2-558a966c48cc.png)

but haven't for the time being.

**Comment by alv67** [comment]
I forgot to give you this info: with this setting an approval is needed to let the merge be done... and the approval can't be done by who makes the PR.

In my own project, where I'm the only developer, I had to remove the approval 😄 or no way to merge the PR.

**Comment by gteti** [comment]
> I forgot to give you this info: with this setting an approval is needed to let the merge be done... and the approval can't be done by who makes the PR.
> 
> In my own project, where I'm the only developer, I had to remove the approval 😄 or no way to merge the PR.

What have you done.... 
![immagine](https://user-images.githubusercontent.com/51110452/150586698-d7a82fc2-bd20-47a5-9d26-ba2144ba8573.png)

**Comment by gteti** [comment]
He will now use this to blackmail us! See he won't merge...
![immagine](https://user-images.githubusercontent.com/51110452/150586855-2b6453da-c73a-47a2-9a35-db10da2aef2e.png)

**Comment by gmacario** [comment]
> He will now use this to blackmail us! See he won't merge... ![immagine](https://user-images.githubusercontent.com/51110452/150586855-2b6453da-c73a-47a2-9a35-db10da2aef2e.png)

That's correct, this is to make sure every PR gets reviewed by a different person before it gets merged.

**Comment by gmacario** [comment]
Anyway for the time being let's keep the policy a little bit more relaxed and uncheck "Require approvals"
