### ISSUE TITLE
[BUG]: Page "Module Index" on arneis.readthedocs.io is broken

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#75]
### Description of the bug

I spotted at least one broken link on the site https://arneis.readthedocs.io/ generated by ReadTheDocs

![image](https://user-images.githubusercontent.com/75182/150487548-bf0c0ca6-8fdf-4102-891f-facf96662ba8.png)

### Steps To Reproduce

1. Go to https://arneis.readthedocs.io/en/latest/index.html#
2. Click on the "Module Index" link

### Expected Result

Something relevant

### Actual Result

Page https://arneis.readthedocs.io/en/latest/py-modindex.html is displayed:

![image](https://user-images.githubusercontent.com/75182/150487284-5abc588a-2ca5-442e-932b-7023eb91e1eb.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @gmacario I would really like to fix it. Can I?

**Comment by gteti** [comment]
> Hey @gmacario I would really like to fix it. Can I?

Of course! Feel free to contribute as much as you want 😄

**Comment by NaincyKumariKnoldus** [comment]
Thanks @gteti I will do it!

**Comment by NaincyKumariKnoldus** [comment]
Hey @gmacario Which link you want here in module index? Can you please give me that link.

**Comment by gmacario** [comment]
> Hey @gmacario I would really like to fix it. Can I?

Hello @NaincyKumariKnoldus,

Sorry for my late reply, and nice to meet you!
I am very excited that you want to contribute to the ARNEIS project.

> Hey @gmacario I would really like to fix it. Can I?

Sure you can 😄. Let me provide you with some more context first.

As you can see, the generated documention for the ARNEIS project (i.e. https://arneis.readthedocs.io/) is a task which is still at a very early stage. I have been leveraging the excellent infrastructure provided by <https://readthedocs.org/> and the Open Source [Sphinx](https://www.sphinx-doc.org/) project.

More specifically I created the website using the `sphinx-quickstart` tool - you can look at [this HOWTO](https://arneis.readthedocs.io/en/latest/howto/howto-configure-arneis-readthedocs-io.html) for the full story.

More specifically, the "Module Index" link on the landing page is caused by the following line in [docs/index.rst](https://github.com/B-AROL-O/ARNEIS/blob/feat/configure-readthedocs/docs/index.rst)

```rst
* :ref:`modindex`
```

I am still a beginner with ReadTheDocs therefore I do not yet know if the module should be configured, or simply removed.

@NaincyKumariKnoldus do you know ReadTheDocs or want to have a look at it? I will appreciate.

**Comment by gmacario** [comment]
@NaincyKumariKnoldus do you plan to look at this during this week?
Otherwise I will postpone the resolution to a future milestone

**Comment by NaincyKumariKnoldus** [comment]
yes @gmacario I will look at this.

**Comment by gmacario** [comment]
No updates received so far, postponing to next sprint

**Comment by gmacario** [comment]
@NaincyKumariKnoldus since I did not see updates on this bug I applied a quick-and-dirty workaround with #168.

Please feel free to improve it, or look after other [unassigned open issues in ARNEIS backlog](https://github.com/B-AROL-O/ARNEIS/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee). Thanks!
