### ISSUE TITLE
[FEAT]: Create an online folder to save Images for training/validation purpose

### ISSUE THREAD

**Issue by gteti** [B-AROL-O/ARNEIS#76]
### Description

Create an online folder in the Cloud to save Images for training/validation purpose

**Comment by rishvantsingh** [comment]
Do i have to create the folder in the project repo ?

**Comment by gteti** [comment]
> Do i have to create the folder in the project repo ?

Hello, no, you don't have to. If it was a simple folder in the repo, I would have done that myself 😄 
I was asking @gmacario to create a folder in the cloud to add there the images we will take to train the NN.

Thank you for trying to help!

**Comment by gmacario** [comment]
@gteti based on a preliminary investigation I found a few options to provide you with what you would need.

Please read [this article](https://www.itproportal.com/features/microsoft-cloud-storage-is-onedrive-or-azure-right-for-your-business/) and let me know which option you prefer.

**Comment by gteti** [comment]
For now, since we don't have all things clear yet, we can use our own storage folder with a "container" where to try to run the code. I've seen on azure calculator that a North Europe machine for 31 days is 79$. What do you guys think ?
https://azure.microsoft.com/it-it/pricing/calculator/

![image](https://user-images.githubusercontent.com/51110452/151166599-90064a32-95cc-4dd8-95c3-b161410c8b40.png)

I've also asked more info on my created issue in depthai-ml-training.

**Comment by gmacario** [comment]
> What do you guys think ?

I think that one of the reasons why the OpenCV contest organizers decided to grant us 900+ US$ of credits in Azure services is that we should need them to complete Phase 2 😉 

That being said, I am fine if you do not want to activate any specific service for the moment.

However, in case any of us would need some in the future, I have created in advance #98 to request your individual Azure account  name (that is, the user name) and a public SSH key so I can grant you the service you will request.

Closing for now, please reopen or (better) create a more specific issue in the future
