### ISSUE TITLE
Try ARNEIS codebase on a 64-bit OS

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#8]
Follow-up to #6

Alternatives:
* https://downloads.raspberrypi.org/raspios_arm64/images/
* [Ubuntu Desktop for Raspberry Pi](https://ubuntu.com/Raspberry-pi)
* [HypriotOS](https://blog.hypriot.com/)
* ...

**Comment by gmacario** [comment]
If you want to try Ubuntu Desktop on your Raspberry Pi first have a look at <https://ubuntu.com/tutorials/install-ubuntu-desktop>

**Comment by gmacario** [comment]
Re: Raspberry Pi OS please see https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by gteti** [comment]
They said that some programs are not yet working with a Raspberry Pi 64 bit OS. So maybe not ALL will work with this version.
🤞

**Comment by gmacario** [comment]
> They said that some programs are not yet working with a Raspberry Pi 64 bit OS. So maybe not ALL will work with this version. 🤞

Right, more specifically it looks like the GPU acceleration of the Raspberry Pi may be still lagging behind.
That's why I am not planning to prioritize a lot on this task, until this will be a hard requirement of the [overall architecture of the ARNEIS project](https://arneis.readthedocs.io/en/latest/architecture/arneis-sysarch.html).

**Comment by gmacario** [comment]
Performance benchmarks between Raspberry Pi OS 32 and 64-bIt
https://www.phoronix.com/scan.php?page=article&item=raspberrypi-32bit-64bit&num=1

**Comment by gmacario** [comment]
Trying Raspberry Pi OS 64-bit on a Raspberry Pi 3B+

Launch Raspberry Pi Images to write the MicroSDHC image

![image](https://user-images.githubusercontent.com/75182/160211408-0b96f953-1d5d-47b8-afeb-0fb9a44425c4.png)

**Comment by gmacario** [comment]
MicroSDHC preparation complete

![image](https://user-images.githubusercontent.com/75182/160212651-9adf2c90-c549-4097-a195-761380a0e311.png)

**Comment by gmacario** [comment]
Tests currently ongoing using a Raspberry Pi 3B+ with Raspberry Pi OS 64-bit and comparing results with the baseline https://arneis.readthedocs.io/en/latest/howto/howto-prepare-rpi4b-for-arneis.html

My verifications at the moment are focused on the performances of Raspberry Pi OS 64-bit when the device is used as a k3s Agent Node as described in https://arneis.readthedocs.io/en/latest/howto/howto-install-k3s-for-arneis.html#add-a-new-agent-node-to-the-cluster

Let's keep the issue open until next week. By that time I should also be able to complete related https://github.com/B-AROL-O/ARNEIS/pull/277 with updates or integrations to the existing set of ARNEIS HOWTOs.
