### ISSUE TITLE
[FEAT]: Implement preview on readthedocs for Pull Requests

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#85]
### Description

In order to more easily validate Pull Requests it would be great to configure some GitHub action or something like that to implement a preview feature on Pull Requests

### Additional Information

* The action should deploy a static website to reflect the contents <https://arneis.readthedocs.org> if the PR gets merged
* The preview website should be accessible on a different URL than the official <https://arneis.readthedocs.org>
* A bot should comment inside the PR with the status of the site build and the link to the preview website if the build completes successfully
* If the build of the preview website fails, merge of the PR should be blocked
* The preview feature should work on multiple concurrent pull requests

**Comment by alv67** [comment]
Instruction for activating the PR preview:

1. In your _Read the Docs_ project page select the `Admin` menu
<img width="846" alt="Schermata 2022-01-25 alle 18 36 42" src="https://user-images.githubusercontent.com/25162080/151029713-e7ef6360-e1b7-4f0f-9a8c-0ec154701581.png">


2. In `Advanced Settings` select **Build pull requests for this project**
<img width="829" alt="Schermata 2022-01-25 alle 18 40 42" src="https://user-images.githubusercontent.com/25162080/151030087-5fa2549e-2235-4e86-83ad-be31bb1f3294.png">

3. That's all. Automagically for each pull request an automatic check that compiles the document on _Read The Docs_ is added. You can check the result of this compilation in the `Detail` information for this check.
<img width="730" alt="Schermata 2022-01-25 alle 18 52 38" src="https://user-images.githubusercontent.com/25162080/151031987-2e64c678-0638-43a9-90c0-f965b2ede3c4.png">

**Comment by alv67** [comment]
@gmacario now is your turn!!

**Comment by gmacario** [comment]
> @gmacario now is your turn!!

Thanks @alv67, I will give it a try
