### ISSUE TITLE
[FEAT]: Design motorization of conveyor

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#87]
### Description

@alv67 please refine

**Comment by alv67** [comment]
First idea for the gearing and the motor position.

![bottle-conveyor-gearing-idea](https://user-images.githubusercontent.com/25162080/151717791-72236a7f-9260-47a4-a0b9-4203fc358e34.png)

**Comment by alv67** [comment]
The released version differ in part from the first idea.

1. used an XL motor
2. now the motor is part of the frame structure giving more stability
3. only 3 gears are used

![bottle-conveyor-20220206](https://user-images.githubusercontent.com/25162080/152682250-b5aaf9ed-fac3-4470-a27f-b8a8631bb6fd.png)

> Note:
>
> I suppose this version will work better and can be used to apply more force to the conveyor
