### ISSUE TITLE
[FEAT]: Complete full path of the ARNEIS conveyor 

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#88]
### Description

Design and realize a complete ring path for the bottles on the conveyor.

In this path all the remaining (not selected) bottles continues to be on motion.
In the path there will be a exit windows where selected bottle will come out, and a feeding window where new bottles can enter in the path.

**Comment by alv67** [comment]
This engineering need "real" bricks so I will posticipate to [dev-cw07](https://github.com/B-AROL-O/ARNEIS/milestone/6) Milestone

**Comment by alv67** [comment]
Done,

TODO the CAD project.

As a proof see this short video

https://user-images.githubusercontent.com/25162080/155892975-eafeade1-e125-40a9-a745-ec8975c725e2.mp4
