### ISSUE TITLE
[FEAT]: Create docs/bibliography.md

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#92]
### Description

Create a page with recommended bibliography, list of acronyms used in the project, etc.

### Additional Information

Here are some initial links which may be useful to add:

* https://itlug.org/glossario/

**Comment by alv67** [comment]
Some links useful to add:

[LEGO Wireless Protocol 3.0.00](https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#document-index)
[Controlling the Lego Technics Hub (Hub 2) via Bluetooth (btle) using a Rasperry Pi 4B](https://dietrichchristopeit.github.io/lego-pi-docs/#controlling-the-lego-technics-hub-hub-2-via-bluetooth-btle-using-a-rasperry-pi-4b)

**Comment by gmacario** [comment]
https://www.clivemaxfield.com/fundamentals-ai-anns-ml-dl-and-dnns/
