### ISSUE TITLE
[FEAT]: Remove the Ads on arneis.readthedocs.io

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#95]
### Description

As of today https://arneis.readthedocs.io/ is configured an Advertisement on each page - example

![image](https://user-images.githubusercontent.com/75182/151244244-51a9bcb2-c74d-4b90-b5c9-2e9e19532802.png)

As a matter of fact I did not do anything to have the ads show up - this came from the default configuration of ReadTheDocs which I created as explained in https://arneis.readthedocs.io/en/latest/howto/howto-configure-arneis-readthedocs-io.html

If anyone happens to know how to get rid of them, please comment here or create a linked Pull Request.

**Comment by gmacario** [comment]
Just found on [docs.readthedocs.io](https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#:~:text=Go%20to%20the%20drop%20down,can%20deselect%20See%20paid%20advertising.):

![image](https://user-images.githubusercontent.com/75182/151304410-db4ed545-ca6c-40b3-b8ec-73bdcf5816fa.png)

**Comment by gteti** [comment]
I don't know if they are avoidable at all, since they may come with the whole READTHEDOCS. It's probably how they gain finance for keeping the project alive.

**Comment by gmacario** [comment]
> I don't know if they are avoidable at all, since they may come with the whole READTHEDOCS. It's probably how they gain finance for keeping the project alive.

Right, for the time being I just followed the official instructions configured the project ARNEIS.readthedocs.io to limit advertising to Open Source Projects. Please see the linked PR
