### ISSUE TITLE
[FEAT]: Create and share Azure account ID and public SSH key

### ISSUE THREAD

**Issue by gmacario** [B-AROL-O/ARNEIS#98]
### Description

In case you should be granted specific privileges on Azure cloud infrastructure and/or other services please comment adding

* The email which you used to register to Azure
* A public SSH key (of which only you have the corresponding private key)

**Comment by gteti** [comment]
I don't have an email registered there yet. Is it mandatory to access the cloud VM ?


My public key is:
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd106LHawJhe2TB4h9Mh9HrShamH6UqdsuniIm+7LXjYJjB1Sq5JVaDueEMdNOAeiEOzHcnPyqCfz0QiLoGT97cSI8I+Q+WspCtS/v8via8GkuyAMs8KJVEeSfH9iCEeLjbHGjC0UMVN8GaMBbgBYNSDOS1oF3OJAbX0ebny7nf5NDebEdX2VJcmuIJsUeC88pdp6g09MnnXodRVQkJ3lQtqJHIVz/j+U578qgZAJn14wk5Ojv01+Wpos+uJ2OskUp81N/xbiwZPo2byyl3RjToPOVgR0c6WsVKUNnAGEn1l4PYNOfvAj73ndowJHsoBCPA771n++6Q5rwj2S+696qGyrPd3U+8qfEVM09/UN1FZO89ZGiJ1XYK7Ig+60q9aQsbEGJlhut+tG8Dypf50q1XFfQFQNHXcNgJHeGOjcnetZFnt+GlzyCdjKSeC6+wjMoZEx4RpP5qdaibELcebO8J8P2ZFM+OuSFay54PZhLsDRQ/LeCu4EMZigzFZwBl+M= Mio@DESKTOP-7MJ41MV`

**Comment by gteti** [comment]
The reason why I didn't want to register an account yet (or if it was avoidable) is:
![image](https://user-images.githubusercontent.com/51110452/151551442-7d80d225-19b3-4bbc-997f-553c3212529f.png)

To not lose the 200 USD offered in 30 days.

**Comment by gmacario** [comment]
Assigning to @alv67 asking also to him

> * The email which you used to register to Azure
> * A public SSH key (of which only you have the corresponding private key)

**Comment by alv67** [comment]
Assigning to @gmacario with requested information:

- registered Azure with my github : alv67.web@gmail.com
- my public key is:

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvsYfICuHJEwSXw61e1fq4uIWDrJI3QeaktLtscULJn2u3LFyd4IuDGVy4QtLhwUZUuKFvxB2AhCeqY7Etj5nUnhaHguWsQnFgQFiP7kZFOfaIP/Q2qCAHdaUkaEmLeV2aC/UZKaMLD3Sbunt+X95+//JPawbZe8DJDYhbN/Rltq4eM2h523ZnAuAugavKB8KKCTpNOB50fpMKeXmqqQuiIgohhFGaGBehum9t5S/hA42tdoE0UELug0fDHf3/1Rb6zxZEC8VNK6UuhweyQa81lV7LIhQM0R5OHkbfrG2CBOlTBoTXsuqjvM86EamknGtSP+v+9hEFTEa2ZEgb049U4G7wC9UEIcys7KDmYr2MREtcXkQdaaOE10U8VsHoT9CmIstTdPM5YOenG+HPG2hOvkm0M7gOeGnJ63pbfgsOhCbBwXKsqhqaNBuNxieeb3a5MuY/yl4zbZJ1VYuElAlu/W/hGbOqjde54EIx6EO213BgCGzAwYmob3EoUlZpajc= alessandro@iMac-di-Alessandro.local

**Comment by gmacario** [comment]
Thanks @alv67 and @gteti
We are now set, if you need any Azure resources just create a new issue on https://github.com/B-AROL-O/ARNEIS/issues and assign it to me.

Closing
